apiVersion: apps/v1
kind: Deployment
metadata:
  name: Anju-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Anju-springboot
  template:
    metadata:
      labels:
        app: Anju-springboot
    spec:
      containers:
        - name: springboot
          image: anjuyadav73/anju-docker-demo:anju-docker-image
          ports:
            - containerPort: 8085
          env:
            - name: PORT
              value: "8085"
---
apiVersion: v1
kind: Service
metadata:
  name: Anju-springboot
spec:
  type: NodePort
  ports:
    - port: 85
      targetPort: 8085
  selector:
    app: Anju-springboot
